version: '3.8'

services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    environment:
      DATABASE_CLIENT: pg
      DATABASE_HOST: dpg-cts2a7a3esus73dlusvg-a.ohio-postgres.render.com
      DATABASE_PORT: 5432
      DATABASE_NAME: directus_db_o1pz
      DATABASE_USER: directus_db_o1pz_user
      DATABASE_PASSWORD: JtkjlmoJpKIPrM41tly7x6SrHG2xV4VJ
    volumes:
      - directus-data:/data

volumes:
  directus-data:
